Metadata:
  ProjectName: pxp-omp-playwright-automation
  ProjectKey: 
  GitRepoUrl: https://bitbucket.csod.com/scm/ent-pxp/pxp-omp-playwright-automation.git
  TemplateType: PK_PRODUCT_FREESTYLE
  Features: 
  Metadata:
    description: omp-playwright-automation
  Branch: 
